apiVersion: v1
kind: Namespace
metadata:
  name: rightsizing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rightsizing
  name: rightsizing-forecast-server
  labels:
    app: rightsizing-forecast-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rightsizing-forecast-server
  template:
    metadata:
      labels:
        app: rightsizing-forecast-server
    spec:
      containers:
      - name: server
        image: tmaxcloudck/rightsizing-forecast-server:test
        ports:
        - containerPort: 50051
        command: [ "python", "/app/rightsizing_server.py" ]

---
apiVersion: v1
kind: Service
metadata:
  namespace: rightsizing
  name: rightsizing-forecast-server-svc
spec:
  selector:
    app: rightsizing-forecast-server
  ports:
    - protocol: TCP
      port: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rightsizing
  name: rightsizing-api-server
  labels:
    app: rightsizing-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rightsizing-api-server
  template:
    metadata:
      labels:
        app: rightsizing-api-server
    spec:
      containers:
      - name: api-server
        image: tmaxcloudck/rightsizing-api-server:test
        ports:
        - containerPort: 8000
        args:
          - '-l'
          - '/log'
          - '-m'
          - 'debug'
          - '--grpc-host'
          - 'rightsizing-forecast-server-svc.rightsizing.svc.cluster.local'
        volumeMounts:
          - mountPath: /log
            name: log-volume
        env:
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: rightsizing-api-server-cm
                key: HOST
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: rightsizing-api-server-cm
                key: PORT
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: rightsizing-api-server-cm
                key: USER
          - name: PASSWORD
            valueFrom:
              configMapKeyRef:
                name: rightsizing-api-server-cm
                key: PASSWORD
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: rightsizing-api-server-cm
                key: DATABASE
          - name: BROKER
            valueFrom:
              configMapKeyRef:
                name: rightsizing-api-server-cm
                key: BROKER
          - name: RESULT_BACKEND
            valueFrom:
              configMapKeyRef:
                name: rightsizing-api-server-cm
                key: RESULT_BACKEND
      volumes:
        - name: log-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: rightsizing
  name: rightsizing-api-server-svc
spec:
  type: NodePort
  selector:
    app: rightsizing-api-server
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: rightsizing
  name: rightsizing-api-server-cm
data:
  HOST: "promscale.monitoring.svc.cluster.local"
  PORT: "5432"
  USER: "postgres"
  PASSWORD: "1234"
  DATABASE: "postgres"
  BROKER: "redis://redis.rightsizing.svc.cluster.local:6379" 
  RESULT_BACKEND: "redis://redis.rightsizing.svc.cluster.local:6379" 

