# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rightsizing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rightsizing.proto',
  package='rightsizing',
  syntax='proto3',
  serialized_options=b'Z\013rightsizing\310\342\036\001\320\342\036\001\340\342\036\001\300\343\036\001\310\343\036\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11rightsizing.proto\x12\x0brightsizing\x1a\x14gogoproto/gogo.proto\"T\n\x0eTimeSeriesData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\ndatapoints\x18\x02 \x03(\x0b\x32 .rightsizing.TimeSeriesDatapoint\"7\n\x13TimeSeriesDatapoint\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\".\n\x12RightsizingRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x01\"B\n\x13RightsizingResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\x01\"M\n\x0f\x46orecastRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12.\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32 .rightsizing.TimeSeriesDatapoint\"\xad\x01\n\x10\x46orecastResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x34\n\x06result\x18\x03 \x03(\x0b\x32$.rightsizing.ForecastResponse.Result\x1a\x46\n\x06Result\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32 .rightsizing.TimeSeriesDatapoint2a\n\x0bRightsizing\x12R\n\x0bRightsizing\x12\x1f.rightsizing.RightsizingRequest\x1a .rightsizing.RightsizingResponse\"\x00\x32U\n\x08\x46orecast\x12I\n\x08\x46orecast\x12\x1c.rightsizing.ForecastRequest\x1a\x1d.rightsizing.ForecastResponse\"\x00\x42!Z\x0brightsizing\xc8\xe2\x1e\x01\xd0\xe2\x1e\x01\xe0\xe2\x1e\x01\xc0\xe3\x1e\x01\xc8\xe3\x1e\x01\x62\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_TIMESERIESDATA = _descriptor.Descriptor(
  name='TimeSeriesData',
  full_name='rightsizing.TimeSeriesData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rightsizing.TimeSeriesData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datapoints', full_name='rightsizing.TimeSeriesData.datapoints', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=140,
)


_TIMESERIESDATAPOINT = _descriptor.Descriptor(
  name='TimeSeriesDatapoint',
  full_name='rightsizing.TimeSeriesDatapoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='rightsizing.TimeSeriesDatapoint.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='rightsizing.TimeSeriesDatapoint.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=197,
)


_RIGHTSIZINGREQUEST = _descriptor.Descriptor(
  name='RightsizingRequest',
  full_name='rightsizing.RightsizingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rightsizing.RightsizingRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='rightsizing.RightsizingRequest.data', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=245,
)


_RIGHTSIZINGRESPONSE = _descriptor.Descriptor(
  name='RightsizingResponse',
  full_name='rightsizing.RightsizingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rightsizing.RightsizingResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='rightsizing.RightsizingResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='rightsizing.RightsizingResponse.result', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=313,
)


_FORECASTREQUEST = _descriptor.Descriptor(
  name='ForecastRequest',
  full_name='rightsizing.ForecastRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rightsizing.ForecastRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='rightsizing.ForecastRequest.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=315,
  serialized_end=392,
)


_FORECASTRESPONSE_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='rightsizing.ForecastResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rightsizing.ForecastResponse.Result.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='rightsizing.ForecastResponse.Result.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=568,
)

_FORECASTRESPONSE = _descriptor.Descriptor(
  name='ForecastResponse',
  full_name='rightsizing.ForecastResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rightsizing.ForecastResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='rightsizing.ForecastResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='rightsizing.ForecastResponse.result', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FORECASTRESPONSE_RESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=568,
)

_TIMESERIESDATA.fields_by_name['datapoints'].message_type = _TIMESERIESDATAPOINT
_FORECASTREQUEST.fields_by_name['data'].message_type = _TIMESERIESDATAPOINT
_FORECASTRESPONSE_RESULT.fields_by_name['data'].message_type = _TIMESERIESDATAPOINT
_FORECASTRESPONSE_RESULT.containing_type = _FORECASTRESPONSE
_FORECASTRESPONSE.fields_by_name['result'].message_type = _FORECASTRESPONSE_RESULT
DESCRIPTOR.message_types_by_name['TimeSeriesData'] = _TIMESERIESDATA
DESCRIPTOR.message_types_by_name['TimeSeriesDatapoint'] = _TIMESERIESDATAPOINT
DESCRIPTOR.message_types_by_name['RightsizingRequest'] = _RIGHTSIZINGREQUEST
DESCRIPTOR.message_types_by_name['RightsizingResponse'] = _RIGHTSIZINGRESPONSE
DESCRIPTOR.message_types_by_name['ForecastRequest'] = _FORECASTREQUEST
DESCRIPTOR.message_types_by_name['ForecastResponse'] = _FORECASTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeSeriesData = _reflection.GeneratedProtocolMessageType('TimeSeriesData', (_message.Message,), {
  'DESCRIPTOR' : _TIMESERIESDATA,
  '__module__' : 'rightsizing_pb2'
  # @@protoc_insertion_point(class_scope:rightsizing.TimeSeriesData)
  })
_sym_db.RegisterMessage(TimeSeriesData)

TimeSeriesDatapoint = _reflection.GeneratedProtocolMessageType('TimeSeriesDatapoint', (_message.Message,), {
  'DESCRIPTOR' : _TIMESERIESDATAPOINT,
  '__module__' : 'rightsizing_pb2'
  # @@protoc_insertion_point(class_scope:rightsizing.TimeSeriesDatapoint)
  })
_sym_db.RegisterMessage(TimeSeriesDatapoint)

RightsizingRequest = _reflection.GeneratedProtocolMessageType('RightsizingRequest', (_message.Message,), {
  'DESCRIPTOR' : _RIGHTSIZINGREQUEST,
  '__module__' : 'rightsizing_pb2'
  # @@protoc_insertion_point(class_scope:rightsizing.RightsizingRequest)
  })
_sym_db.RegisterMessage(RightsizingRequest)

RightsizingResponse = _reflection.GeneratedProtocolMessageType('RightsizingResponse', (_message.Message,), {
  'DESCRIPTOR' : _RIGHTSIZINGRESPONSE,
  '__module__' : 'rightsizing_pb2'
  # @@protoc_insertion_point(class_scope:rightsizing.RightsizingResponse)
  })
_sym_db.RegisterMessage(RightsizingResponse)

ForecastRequest = _reflection.GeneratedProtocolMessageType('ForecastRequest', (_message.Message,), {
  'DESCRIPTOR' : _FORECASTREQUEST,
  '__module__' : 'rightsizing_pb2'
  # @@protoc_insertion_point(class_scope:rightsizing.ForecastRequest)
  })
_sym_db.RegisterMessage(ForecastRequest)

ForecastResponse = _reflection.GeneratedProtocolMessageType('ForecastResponse', (_message.Message,), {

  'Result' : _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR' : _FORECASTRESPONSE_RESULT,
    '__module__' : 'rightsizing_pb2'
    # @@protoc_insertion_point(class_scope:rightsizing.ForecastResponse.Result)
    })
  ,
  'DESCRIPTOR' : _FORECASTRESPONSE,
  '__module__' : 'rightsizing_pb2'
  # @@protoc_insertion_point(class_scope:rightsizing.ForecastResponse)
  })
_sym_db.RegisterMessage(ForecastResponse)
_sym_db.RegisterMessage(ForecastResponse.Result)


DESCRIPTOR._options = None

_RIGHTSIZING = _descriptor.ServiceDescriptor(
  name='Rightsizing',
  full_name='rightsizing.Rightsizing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=570,
  serialized_end=667,
  methods=[
  _descriptor.MethodDescriptor(
    name='Rightsizing',
    full_name='rightsizing.Rightsizing.Rightsizing',
    index=0,
    containing_service=None,
    input_type=_RIGHTSIZINGREQUEST,
    output_type=_RIGHTSIZINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RIGHTSIZING)

DESCRIPTOR.services_by_name['Rightsizing'] = _RIGHTSIZING


_FORECAST = _descriptor.ServiceDescriptor(
  name='Forecast',
  full_name='rightsizing.Forecast',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=669,
  serialized_end=754,
  methods=[
  _descriptor.MethodDescriptor(
    name='Forecast',
    full_name='rightsizing.Forecast.Forecast',
    index=0,
    containing_service=None,
    input_type=_FORECASTREQUEST,
    output_type=_FORECASTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FORECAST)

DESCRIPTOR.services_by_name['Forecast'] = _FORECAST

# @@protoc_insertion_point(module_scope)
